# Generated by Django 2.2.4 on 2019-11-17 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(default='user', max_length=50, unique=True)),
                ('display_name', models.CharField(default='user', max_length=50)),
                ('email', models.CharField(default='', max_length=150)),
                ('access_token', models.CharField(default='', max_length=50)),
                ('refresh_token', models.CharField(default='', max_length=50)),
                ('celery_id', models.CharField(default='', max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(default='channel', max_length=50)),
                ('display_name', models.CharField(default='channel', max_length=50)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
