# Generated by Django 2.2.4 on 2019-11-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='user',
            new_name='users',
        ),
    ]
