# Generated by Django 2.2.4 on 2019-11-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191118_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='colours',
            field=models.TextField(default='["Red", "Firebrick", "Chocolate", "OrangeRed", "Coral", "GoldenRod", "YellowGreen", "Green", "SeaGreen", "SpringGreen", "DodgerBlue", "Blue", "BlueViolet", "HotPink"]'),
        ),
    ]
