# Generated by Django 2.2.4 on 2019-11-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191121_0627'),
        ('main', '0004_user_colours'),
    ]

    operations = [
    ]
